# Azure Key Vault
## Loaded programmatically via SecretClient.
spring.cloud.azure.keyvault.secret.endpoint = https://kv-jaclo.vault.azure.net
## Loaded into the Spring Environment and injected via @Value.
spring.cloud.azure.keyvault.secret.property-sources[0].endpoint = https://kv-jaclo.vault.azure.net